# eslint configuration
parserOptions:
  ecmaVersion: 2018
  sourceType: module
env:
  node: true
  jest: true
extends:
  - 'eslint:recommended'
  - 'airbnb-base'
  - 'prettier'
rules:
  linebreak-style:
    - error
    - unix
